begin;
do $$ declare u uuid=gen_random_uuid();other_u uuid=gen_random_uuid();s uuid;other_s uuid;th uuid;turn uuid;token uuid;result jsonb;ent jsonb;key uuid;begin
 insert into auth.users(id,email,email_confirmed_at) values(u,'consultation-transaction@example.invalid',now()),(other_u,'consultation-other@example.invalid',now());
 insert into public.consultation_subjects(user_id,nickname) values(u,'架空の相談相手') returning id into s;
 insert into public.consultation_subjects(user_id,nickname) values(other_u,'別ユーザー') returning id into other_s;
 insert into public.consultation_threads(user_id,subject_id) values(u,s) returning id into th;
 assert (public.consultation_entitlement(u)->>'remaining')::int=3,'free initial limit';
 result:=public.reserve_consultation(other_u,th,gen_random_uuid(),'他人',gen_random_uuid(),false,false,null);assert result->>'error'='not_found','IDOR';
 assert not public.manage_consultation(u,'move_thread',th,other_s,null,'[]'),'foreign subject move';
 for n in 1..3 loop
 turn:=gen_random_uuid();token:=gen_random_uuid();
 result:=public.reserve_consultation(u,th,turn,'相談'||n,token,false,false,null);assert result->>'error' is null,'reserve';
 assert (public.consultation_entitlement(u)->>'reserved')::int=1,'atomic reservation';
 assert public.reserve_consultation(u,th,turn,'相談'||n,token,false,false,null)->>'error'='busy','duplicate in flight';
 assert not public.finish_consultation(u,turn,gen_random_uuid(),'回答','[]','[]',false,true),'fencing token';
 assert public.finish_consultation(u,turn,token,null,'[]','[]',false,false),'failure released';
 assert (public.consultation_entitlement(u)->>'reserved')::int=0,'failure releases quota';
 result:=public.reserve_consultation(u,th,turn,'相談'||n,token,false,false,null);
 assert public.finish_consultation(u,turn,token,'回答','[]','[]',false,true),'success';
 assert (public.reserve_consultation(u,th,turn,'相談'||n,token,false,false,null)->>'cached')::boolean,'retry cached';
 end loop;
 assert (public.consultation_entitlement(u)->>'used')::int=3,'three successful exchanges';
 assert public.reserve_consultation(u,th,gen_random_uuid(),'4回目',gen_random_uuid(),false,false,null)->>'error'='quota','fourth denied';
 token:=gen_random_uuid();key:=gen_random_uuid();result:=public.reserve_consultation(u,th,turn,'相談3',token,true,false,key);assert result->>'error' is null,'regeneration does not require quota';
 assert public.finish_consultation(u,turn,token,'再生成回答','[]','[]',false,true),'regeneration succeeds';
 assert (public.reserve_consultation(u,th,turn,'相談3',token,true,false,key)->>'cached')::boolean,'regeneration retry cached';
 assert (public.consultation_entitlement(u)->>'used')::int=3,'regeneration not charged';
 turn:=gen_random_uuid();token:=gen_random_uuid();result:=public.reserve_consultation(u,th,turn,'危険',token,false,true,null);assert result->>'error' is null,'safety over quota';
 assert public.finish_consultation(u,turn,token,'安全の案内','[]','[]',true,true),'safety response';
 assert (public.consultation_entitlement(u)->>'used')::int=3,'safety free';
 assert public.manage_consultation(u,'delete_thread',th,null,null,'[]'),'delete history';
 assert not exists(select 1 from public.consultation_turns where thread_id=th and (assistant_text is not null or user_text<>'[削除済み]')),'deleted content gone';
 assert (public.consultation_entitlement(u)->>'used')::int=3,'deletion cannot reset usage';
 update public.consultation_turns set created_at=now()-interval '2 months' where user_id=u;
 assert (public.consultation_entitlement(u)->>'remaining')::int=3,'calendar reset';
 insert into public.billing_customers(user_id,stripe_customer_id) values(u,'cus_transaction_test');
 insert into public.subscriptions(id,user_id,stripe_customer_id,price_version,amount,status,period_start,period_end,paid_through,created_at) values('sub_transaction_test',u,'cus_transaction_test','plus-2026-10-980',980,'active',now()-interval '1 day',now()+interval '29 days',now()+interval '29 days',now());
 assert public.consultation_entitlement(u)->>'plan'='plus','verified subscription entitlement';
 assert (public.consultation_entitlement(u)->>'remaining')::int=30,'plus limit';
 insert into public.consultation_turns(id,user_id,thread_id,user_text,assistant_text,status,charged,plan,period_start,period_end) select gen_random_uuid(),u,th,'架空の完了済み相談','架空の回答','ready',true,'plus',now()-interval '1 day',now()+interval '29 days' from generate_series(1,30);
 assert (public.consultation_entitlement(u)->>'remaining')::int=0,'thirty plus exchanges';
 assert public.reserve_consultation(u,th,gen_random_uuid(),'31回目',gen_random_uuid(),false,false,null)->>'error'='quota','plus 31st denied';
 update public.subscriptions set cancel_at_period_end=true where user_id=u;
 assert public.consultation_entitlement(u)->>'plan'='plus','cancel retains paid period';
 update public.subscriptions set paid_through=now()-interval '1 second',status='past_due' where user_id=u;
 assert public.consultation_entitlement(u)->>'plan'='free','failed unpaid renewal falls back';
 update public.subscriptions set paid_through=now()+interval '29 days',status='canceled' where user_id=u;
 assert public.consultation_entitlement(u)->>'plan'='free','immediate cancellation';
end $$;
rollback;
