-- Additive schema: existing rows default to v1. Only the new application opts into v2.
alter table public.diagnoses add column question_flow_version text not null default 'v1' check (question_flow_version in ('v1','v2')), add column question_flow_json jsonb not null default '{}';
alter table public.diagnosis_questions add column flow_version text not null default 'v1', add column relationship_types jsonb not null default '[]', add column concern_types jsonb not null default '[]', add column phase text not null default 'common' check(phase in ('common','relationship','concern','ai_followup','paid_followup')), add column condition_json jsonb not null default '{}', add column priority int not null default 50, add column max_uses int not null default 1 check(max_uses between 0 and 1), add column followup_group text;
create table public.diagnosis_selected_questions (
 diagnosis_id uuid not null references public.diagnoses(id) on delete cascade,
 question_key text not null, snapshot jsonb not null,
 phase text not null check(phase in ('common','relationship','concern','ai_followup','paid_followup')),
 question_source text not null check(question_source in ('common','relationship','concern','ai_selected','ai_generated','paid_followup')),
 selected_reason text not null, position int not null, is_active boolean not null default true,
 displayed_at timestamptz, answered_at timestamptz, answer text, selected_at timestamptz not null default now(),
 primary key(diagnosis_id,question_key)
);
alter table public.diagnosis_selected_questions enable row level security;
revoke all on public.diagnosis_selected_questions from public,anon,authenticated;
grant all on public.diagnosis_selected_questions to service_role;
-- History is server-only: reason and unused/internal selection data never reach a public API.
create function public.save_question_plan(p_diagnosis uuid,p_flow jsonb,p_questions jsonb) returns void language plpgsql set search_path='' as $$
declare q jsonb; n int;
begin
 perform 1 from public.diagnoses where id=p_diagnosis and question_flow_version='v2' for update;
 if not found then raise exception 'v2 diagnosis required'; end if;
 for q in select value from jsonb_array_elements(p_questions) loop
  insert into public.diagnosis_selected_questions(diagnosis_id,question_key,snapshot,phase,question_source,selected_reason,position)
  values(p_diagnosis,q->>'question_key',q,q->>'phase',q->>'question_source',q->>'selected_reason',(q->>'position')::int)
  on conflict(diagnosis_id,question_key) do update set snapshot=excluded.snapshot,phase=excluded.phase,question_source=excluded.question_source,selected_reason=excluded.selected_reason,position=excluded.position,is_active=true,displayed_at=null,answered_at=null,answer=null,selected_at=now() where not public.diagnosis_selected_questions.is_active;
  get diagnostics n=row_count;
  if n>0 then insert into public.analytics_events(event_name,metadata) values('dynamic_question_selected',jsonb_build_object('diagnosis_id',p_diagnosis,'question_key',q->>'question_key','phase',q->>'phase','source',q->>'question_source')); end if;
 end loop;
 update public.diagnoses set question_flow_json=p_flow,updated_at=now() where id=p_diagnosis;
 if coalesce((p_flow->>'paid_followup_needed')::boolean,false) then
  update public.paid_reports set status=case when coalesce((p_flow->>'paid_completed')::boolean,false) then 'queued' else 'awaiting_answers' end,updated_at=now() where diagnosis_id=p_diagnosis and status in ('queued','awaiting_answers');
 end if;
end $$;
create function public.save_dynamic_answer(p_diagnosis uuid,p_key text,p_answer text) returns void language plpgsql set search_path='' as $$
declare q public.diagnosis_selected_questions; d public.diagnoses; old_answer text; changed boolean;
begin
 select * into d from public.diagnoses where id=p_diagnosis for update;
 select * into q from public.diagnosis_selected_questions where diagnosis_id=p_diagnosis and question_key=p_key and is_active for update;
 if q.question_key is null or length(trim(p_answer))=0 or length(p_answer)>2000 then raise exception 'invalid question or answer'; end if;
 if d.status='safety' then raise exception 'safety stopped'; end if;
 if q.phase='paid_followup' then
  if not exists(select 1 from public.payments where diagnosis_id=p_diagnosis and status='paid') or coalesce((d.question_flow_json->>'paid_completed')::boolean,false) then raise exception 'paid answer not allowed'; end if;
 else
  if exists(select 1 from public.diagnosis_analyses where diagnosis_id=p_diagnosis) or d.status not in ('answering','followup','failed') then raise exception 'answers frozen'; end if;
 end if;
 select answer_text into old_answer from public.diagnosis_answers where diagnosis_id=p_diagnosis and question_key=p_key;
 if old_answer=p_answer then return; end if;
 changed:=old_answer is not null;
 if changed and q.phase in ('common','relationship','concern') then
  -- Re-select only when the person changes an answer; ordinary reload never changes the plan.
  delete from public.diagnosis_answers a using public.diagnosis_selected_questions s where a.diagnosis_id=p_diagnosis and s.diagnosis_id=a.diagnosis_id and s.question_key=a.question_key and s.is_active and (case when q.phase='common' then s.phase<>'common' else s.phase='ai_followup' end);
  update public.diagnosis_selected_questions set is_active=false where diagnosis_id=p_diagnosis and is_active and (case when q.phase='common' then phase<>'common' else phase='ai_followup' end);
  update public.diagnoses set question_flow_json=case when q.phase='common' then '{}'::jsonb else question_flow_json - 'final_checked' end,classification_json=null,followup_json=null,status='answering' where id=p_diagnosis;
 end if;
 insert into public.diagnosis_answers(diagnosis_id,question_id,question_key,question_text,answer_text,is_follow_up)
 values(p_diagnosis,nullif(q.snapshot->>'id','')::uuid,p_key,q.snapshot->>'question_text',p_answer,q.phase in ('ai_followup','paid_followup'))
 on conflict(diagnosis_id,question_key) do update set answer_text=excluded.answer_text,question_text=excluded.question_text;
 update public.diagnosis_selected_questions set answer=p_answer,answered_at=now() where diagnosis_id=p_diagnosis and question_key=p_key;
 insert into public.analytics_events(event_name,metadata) values('dynamic_question_answered',jsonb_build_object('diagnosis_id',p_diagnosis,'question_key',p_key,'phase',q.phase,'edited',changed));
end $$;
create function public.view_dynamic_question(p_diagnosis uuid,p_key text) returns void language plpgsql set search_path='' as $$
declare q public.diagnosis_selected_questions;
begin
 update public.diagnosis_selected_questions set displayed_at=now() where diagnosis_id=p_diagnosis and question_key=p_key and is_active and displayed_at is null returning * into q;
 if q.question_key is not null then insert into public.analytics_events(event_name,metadata) values('dynamic_question_viewed',jsonb_build_object('diagnosis_id',p_diagnosis,'question_key',p_key,'phase',q.phase)); end if;
end $$;
revoke all on function public.save_question_plan(uuid,jsonb,jsonb),public.save_dynamic_answer(uuid,text,text),public.view_dynamic_question(uuid,text) from public,anon,authenticated;
grant execute on function public.save_question_plan(uuid,jsonb,jsonb),public.save_dynamic_answer(uuid,text,text),public.view_dynamic_question(uuid,text) to service_role;

-- Old application instances continue to see only their original public question list.
alter policy active_questions on public.diagnosis_questions using(is_active and flow_version='v1');
alter table public.paid_reports drop constraint paid_reports_status_check;
alter table public.paid_reports add constraint paid_reports_status_check check(status in ('queued','generating','ready','failed','revoked','awaiting_answers'));
-- Versioned candidates; legacy rows and text remain unchanged.
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'v2_relationship','今、相手とはどんな関係ですか？','common','[]'::jsonb,'[]'::jsonb,'relationship','radio','["交際中", "片思い", "友人", "はっきり付き合ってはいない", "元恋人", "マッチングアプリで知り合った", "その他"]'::jsonb,'{}'::jsonb,50,1,null,100,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'v2_duration','知り合って、どのくらいになりますか？','common','[]'::jsonb,'[]'::jsonb,'duration','radio','["1か月未満", "1〜3か月", "3〜6か月", "半年〜1年", "1年以上"]'::jsonb,'{}'::jsonb,50,1,null,101,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'v2_last_meeting','最後に会ったのは、いつ頃ですか？','common','[]'::jsonb,'[]'::jsonb,'last_meeting','radio','["1週間以内", "1か月以内", "1〜3か月前", "3か月以上前", "まだ会っていない"]'::jsonb,'{}'::jsonb,50,1,null,102,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'v2_contact','普段はどのくらい連絡を取っていますか？','common','[]'::jsonb,'[]'::jsonb,'contact','radio','["ほぼ毎日", "週に数回", "週に1回くらい", "月に数回", "今は連絡を取っていない"]'::jsonb,'{}'::jsonb,50,1,null,103,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'v2_initiative','LINEや連絡は、どちらから始めることが多いですか？','common','[]'::jsonb,'[]'::jsonb,'initiative','radio','["相手から来ることが多い", "自分から送ることが多い", "だいたい半々", "よく分からない"]'::jsonb,'{}'::jsonb,50,1,null,104,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'v2_next_meeting','次に会う予定は決まっていますか？','common','[]'::jsonb,'[]'::jsonb,'next_meeting','radio','["日時まで決まっている", "会う話はしている", "まだ決まっていない", "誘ったけれど、断られた・延期になった"]'::jsonb,'{}'::jsonb,50,1,null,105,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'v2_behavior','最近、相手のことで一番気になった出来事を教えてください。','common','[]'::jsonb,'[]'::jsonb,'recent_event','textarea','[]'::jsonb,'{}'::jsonb,50,1,'覚えている範囲で、話せることだけで大丈夫です。',106,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'v2_concern','今、一番気になっているのはどんなことですか？','common','[]'::jsonb,'[]'::jsonb,'concern','radio','["返信が遅くなった", "連絡が減った", "態度が前より冷たく感じる", "次に会う予定が決まらない", "復縁したい", "他の人の存在が気になる", "別れそうで不安", "ふたりの関係をはっきりさせたい", "好意があるのか分からない", "自分の気持ちもまだ整理できていない", "その他"]'::jsonb,'{}'::jsonb,50,1,null,107,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'v2_goal','相手と、これからどんな関係になりたいですか？','common','[]'::jsonb,'[]'::jsonb,'goal','textarea','[]'::jsonb,'{}'::jsonb,50,1,'覚えている範囲で、話せることだけで大丈夫です。',108,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'dating_length','付き合ってどのくらいになりますか？','relationship','["dating"]'::jsonb,'[]'::jsonb,'dating_length','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',109,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'dating_meeting','普段はどのくらいのペースで会っていますか？','relationship','["dating"]'::jsonb,'[]'::jsonb,'meeting_frequency','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',110,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'dating_affection','最近、相手からどんなふうに愛情を伝えてくれますか？','relationship','["dating"]'::jsonb,'[]'::jsonb,'affection','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',111,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'dating_conflict','最近、ケンカや気まずくなった出来事はありましたか？','relationship','["dating"]'::jsonb,'[]'::jsonb,'conflict','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',112,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'dating_life','相手の仕事や生活に、最近変わったことはありますか？','relationship','["dating"]'::jsonb,'[]'::jsonb,'life_change','textarea','[]'::jsonb,'{}'::jsonb,76,1,'覚えている範囲で、話せることだけで大丈夫です。',113,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'dating_future','ふたりのこれからについて、どんな話をしていますか？','relationship','["dating"]'::jsonb,'[]'::jsonb,'future','textarea','[]'::jsonb,'{}'::jsonb,75,1,'覚えている範囲で、話せることだけで大丈夫です。',114,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'dating_change','会う回数は、前と比べて変わりましたか？','relationship','["dating"]'::jsonb,'[]'::jsonb,'meeting_change','radio','["前より増えた", "前より減った", "あまり変わらない", "よく分からない"]'::jsonb,'{}'::jsonb,74,1,null,115,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'crush_alone','ふたりきりで会ったことはありますか？','relationship','["crush"]'::jsonb,'[]'::jsonb,'alone','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',116,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'crush_invite','相手から誘ってくれたことはありますか？','relationship','["crush"]'::jsonb,'[]'::jsonb,'invitation','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',117,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'crush_topics','相手からは、どんな話題を出してくれますか？','relationship','["crush"]'::jsonb,'[]'::jsonb,'topics','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',118,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'crush_partner','相手に恋人がいるか、分かりますか？','relationship','["crush"]'::jsonb,'[]'::jsonb,'partner','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',119,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'crush_romance','恋愛の話をしたとき、相手はどんな様子でしたか？','relationship','["crush"]'::jsonb,'[]'::jsonb,'romance','textarea','[]'::jsonb,'{}'::jsonb,76,1,'覚えている範囲で、話せることだけで大丈夫です。',120,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'crush_difference','他の人とあなたとで、相手の接し方に違いを感じますか？','relationship','["crush"]'::jsonb,'[]'::jsonb,'difference','textarea','[]'::jsonb,'{}'::jsonb,75,1,'覚えている範囲で、話せることだけで大丈夫です。',121,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'friend_alone','ふたりきりで会うことはありますか？','relationship','["friend"]'::jsonb,'[]'::jsonb,'alone','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',122,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'friend_confide','相手から、個人的な相談をされることはありますか？','relationship','["friend"]'::jsonb,'[]'::jsonb,'confide','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',123,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'friend_closer','最近、距離が近くなったと感じた出来事はありますか？','relationship','["friend"]'::jsonb,'[]'::jsonb,'closeness','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',124,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'friend_romance','恋愛の話をすることはありますか？','relationship','["friend"]'::jsonb,'[]'::jsonb,'romance','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',125,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'friend_difference','他の友人への接し方と、違うと感じることはありますか？','relationship','["friend"]'::jsonb,'[]'::jsonb,'difference','textarea','[]'::jsonb,'{}'::jsonb,76,1,'覚えている範囲で、話せることだけで大丈夫です。',126,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'friend_invite','ふたりで会おうと誘うと、相手はどんな反応をしますか？','relationship','["friend"]'::jsonb,'[]'::jsonb,'invitation','textarea','[]'::jsonb,'{}'::jsonb,75,1,'覚えている範囲で、話せることだけで大丈夫です。',127,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'ambiguous_dates','ふたりで会うときは、どんなふうに過ごしていますか？','relationship','["ambiguous"]'::jsonb,'[]'::jsonb,'dates','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',128,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'ambiguous_timing','相手から連絡が来るのは、どんな時間帯が多いですか？','relationship','["ambiguous"]'::jsonb,'[]'::jsonb,'timing','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',129,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'ambiguous_convenience','会う予定は、あなたの都合も聞いて決めてくれますか？','relationship','["ambiguous"]'::jsonb,'[]'::jsonb,'convenience','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',130,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'ambiguous_talk','ふたりの関係について、相手と話したことはありますか？','relationship','["ambiguous"]'::jsonb,'[]'::jsonb,'relationship_talk','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',131,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'ambiguous_introduction','相手は周りの人に、あなたをどう紹介していますか？','relationship','["ambiguous"]'::jsonb,'[]'::jsonb,'introduction','textarea','[]'::jsonb,'{}'::jsonb,76,1,'覚えている範囲で、話せることだけで大丈夫です。',132,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'ambiguous_boundary','ふたりで過ごすうえで、あなたが大切にしたいことは何ですか？','relationship','["ambiguous"]'::jsonb,'[]'::jsonb,'boundary','textarea','[]'::jsonb,'{}'::jsonb,75,1,'覚えている範囲で、話せることだけで大丈夫です。',133,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'ex_when','別れたのは、いつ頃ですか？','relationship','["ex"]'::jsonb,'[]'::jsonb,'breakup_time','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',134,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'ex_who','別れを切り出したのは、どちらでしたか？','relationship','["ex"]'::jsonb,'[]'::jsonb,'breakup_who','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',135,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'ex_reason','別れることになった一番大きな理由は、何だったと思いますか？','relationship','["ex"]'::jsonb,'[]'::jsonb,'breakup_reason','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',136,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'ex_improved','別れにつながったことは、今はどのくらい変わっていますか？','relationship','["ex"]'::jsonb,'[]'::jsonb,'improvement','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',137,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'ex_partner','相手に新しい恋人がいるか、分かりますか？','relationship','["ex"]'::jsonb,'[]'::jsonb,'partner','textarea','[]'::jsonb,'{}'::jsonb,76,1,'覚えている範囲で、話せることだけで大丈夫です。',138,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'ex_last_words','最後は、どんなやり取りで終わりましたか？','relationship','["ex"]'::jsonb,'[]'::jsonb,'last_words','textarea','[]'::jsonb,'{}'::jsonb,75,1,'覚えている範囲で、話せることだけで大丈夫です。',139,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'app_count','実際には何回会いましたか？','relationship','["matching_app"]'::jsonb,'[]'::jsonb,'meeting_count','radio','["まだ会っていない", "1回", "2回", "3回以上"]'::jsonb,'{}'::jsonb,80,1,null,140,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'app_after','初めて会った後、連絡の様子はどう変わりましたか？','relationship','["matching_app"]'::jsonb,'[]'::jsonb,'after_date','textarea','[]'::jsonb,'{"key": "v2_last_meeting", "not_equals": ["まだ会っていない"]}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',141,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'app_mood','会っているときの会話は、どんな雰囲気でしたか？','relationship','["matching_app"]'::jsonb,'[]'::jsonb,'meeting_mood','textarea','[]'::jsonb,'{"key": "v2_last_meeting", "not_equals": ["まだ会っていない"]}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',142,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'app_schedule','会う日を決めるとき、相手からも提案してくれますか？','relationship','["matching_app"]'::jsonb,'[]'::jsonb,'scheduling','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',143,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'app_topics','相手からは、どんなことを聞かれますか？','relationship','["matching_app"]'::jsonb,'[]'::jsonb,'topics','textarea','[]'::jsonb,'{}'::jsonb,76,1,'覚えている範囲で、話せることだけで大丈夫です。',144,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'app_before','会う前は、相手とどんなやり取りをしていましたか？','relationship','["matching_app"]'::jsonb,'[]'::jsonb,'before_date','textarea','[]'::jsonb,'{"key": "v2_last_meeting", "not_equals": ["まだ会っていない"]}'::jsonb,75,1,'覚えている範囲で、話せることだけで大丈夫です。',145,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'other_context','相手とは、どんなきっかけで知り合いましたか？','relationship','["other"]'::jsonb,'[]'::jsonb,'context','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',146,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'other_alone','ふたりで話す機会は、どんなときにありますか？','relationship','["other"]'::jsonb,'[]'::jsonb,'alone','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',147,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'other_distance','普段のふたりの距離感を、どう感じていますか？','relationship','["other"]'::jsonb,'[]'::jsonb,'closeness','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',148,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'other_boundary','相手との関わりで、大切にしたいことは何ですか？','relationship','["other"]'::jsonb,'[]'::jsonb,'boundary','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',149,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'other_life','相手の仕事や生活について、分かっていることはありますか？','relationship','["other"]'::jsonb,'[]'::jsonb,'life_change','textarea','[]'::jsonb,'{}'::jsonb,76,1,'覚えている範囲で、話せることだけで大丈夫です。',150,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'reply_since','返信が遅くなったと感じ始めたのは、だいたいいつ頃ですか？','concern','[]'::jsonb,'["slow_reply"]'::jsonb,'change_since','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',151,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'reply_before','前は、どのくらいで返信が来ていましたか？','concern','[]'::jsonb,'["slow_reply"]'::jsonb,'reply_before','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',152,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'reply_now','今は、返信までどのくらいかかることが多いですか？','concern','[]'::jsonb,'["slow_reply"]'::jsonb,'reply_now','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',153,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'reply_content','返信の内容にも、前と違うところはありますか？','concern','[]'::jsonb,'["slow_reply"]'::jsonb,'reply_content','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',154,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'reply_meeting','実際に会ったときの相手の様子は、前と比べてどうですか？','concern','[]'::jsonb,'["slow_reply"]'::jsonb,'meeting_mood','textarea','[]'::jsonb,'{}'::jsonb,76,1,'覚えている範囲で、話せることだけで大丈夫です。',155,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'contact_amount','相手からの連絡は、前と比べてどのくらい減りましたか？','concern','[]'::jsonb,'["decreased_contact"]'::jsonb,'contact_change','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',156,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'contact_since','連絡が減ったと感じ始めたのは、いつ頃ですか？','concern','[]'::jsonb,'["decreased_contact"]'::jsonb,'change_since','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',157,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'contact_busy','忙しい理由について、相手から何か聞いていますか？','concern','[]'::jsonb,'["decreased_contact"]'::jsonb,'life_change','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',158,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'contact_meetings','会う回数にも変化はありますか？','concern','[]'::jsonb,'["decreased_contact"]'::jsonb,'meeting_change','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',159,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'cold_since','前と違うと感じ始めたのは、いつ頃ですか？','concern','[]'::jsonb,'["cold_behavior"]'::jsonb,'change_since','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',160,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'cold_channels','会っているときとLINEで、相手の様子に違いはありますか？','concern','[]'::jsonb,'["cold_behavior"]'::jsonb,'channel_difference','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',161,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'cold_conflict','最近、気まずくなったきっかけはありましたか？','concern','[]'::jsonb,'["cold_behavior"]'::jsonb,'conflict','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',162,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'cold_life','最近、相手の仕事や生活に変わったことはありますか？','concern','[]'::jsonb,'["cold_behavior"]'::jsonb,'life_change','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',163,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'date_invited','次に会おうと、あなたから誘いましたか？','concern','[]'::jsonb,'["no_next_date"]'::jsonb,'invitation','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',164,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'date_response','誘ったとき、相手はどんな言葉で答えてくれましたか？','concern','[]'::jsonb,'["no_next_date"]'::jsonb,'invitation_response','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',165,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'date_alternative','相手から、別の日を提案してくれましたか？','concern','[]'::jsonb,'["no_next_date"]'::jsonb,'alternative_date','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',166,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'date_busy','予定が合わない理由について、相手から何か聞いていますか？','concern','[]'::jsonb,'["no_next_date"]'::jsonb,'life_change','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',167,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'reconcile_reason','別れることになった一番大きな理由は、何だったと思いますか？','concern','[]'::jsonb,'["reconciliation"]'::jsonb,'breakup_reason','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',168,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'reconcile_improvement','別れにつながったことは、今はどのくらい変わっていますか？','concern','[]'::jsonb,'["reconciliation"]'::jsonb,'improvement','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',169,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'reconcile_past','相手は、付き合っていた頃のことをどんなふうに話しますか？','concern','[]'::jsonb,'["reconciliation"]'::jsonb,'past_talk','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',170,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'reconcile_told','もう一度付き合いたい気持ちは、相手に伝えましたか？','concern','[]'::jsonb,'["reconciliation"]'::jsonb,'reconciliation_talk','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',171,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'reconcile_boundary','連絡を取ることについて、相手から希望を伝えられていますか？','concern','[]'::jsonb,'["reconciliation"]'::jsonb,'boundary','textarea','[]'::jsonb,'{}'::jsonb,76,1,'覚えている範囲で、話せることだけで大丈夫です。',172,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'jealous_source','気になっていることは、相手から聞いた話ですか？','concern','[]'::jsonb,'["jealousy"]'::jsonb,'source','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',173,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'jealous_history','その人のことは、以前から話に出ていましたか？','concern','[]'::jsonb,'["jealousy"]'::jsonb,'other_history','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',174,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'jealous_asked','気になっていることを、相手に聞いたことはありますか？','concern','[]'::jsonb,'["jealousy"]'::jsonb,'asked','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',175,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'jealous_change','その頃から、あなたへの接し方に変化はありますか？','concern','[]'::jsonb,'["jealousy"]'::jsonb,'behavior_change','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',176,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'breakup_words','ふたりの関係について、最近相手からどんな言葉がありましたか？','concern','[]'::jsonb,'["breakup_risk"]'::jsonb,'last_words','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',177,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'breakup_conflict','ケンカの回数や内容は、前と比べて変わりましたか？','concern','[]'::jsonb,'["breakup_risk"]'::jsonb,'conflict','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',178,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'breakup_request','相手から、変えてほしいと言われたことはありますか？','concern','[]'::jsonb,'["breakup_risk"]'::jsonb,'request','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',179,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'breakup_affection','相手からの愛情表現に、変化はありますか？','concern','[]'::jsonb,'["breakup_risk"]'::jsonb,'affection','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',180,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'breakup_future','ふたりのこれからについて話すと、相手はどんな様子ですか？','concern','[]'::jsonb,'["breakup_risk"]'::jsonb,'future','textarea','[]'::jsonb,'{}'::jsonb,76,1,'覚えている範囲で、話せることだけで大丈夫です。',181,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'commit_talk','ふたりの関係について、相手に聞いたことはありますか？','concern','[]'::jsonb,'["commitment"]'::jsonb,'relationship_talk','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',182,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'commit_response','関係について話したとき、相手はどんな反応でしたか？','concern','[]'::jsonb,'["commitment"]'::jsonb,'relationship_response','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',183,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'commit_future','相手から、ふたりのこれからの話をすることはありますか？','concern','[]'::jsonb,'["commitment"]'::jsonb,'future','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',184,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'commit_boundary','どんな関係なら、あなたは安心して過ごせそうですか？','concern','[]'::jsonb,'["commitment"]'::jsonb,'boundary','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',185,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'mixed_invite','相手から、ふたりで会おうと誘われることはありますか？','concern','[]'::jsonb,'["mixed_signals"]'::jsonb,'invitation','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',186,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'mixed_distance','会っているときの距離感を、どう感じていますか？','concern','[]'::jsonb,'["mixed_signals"]'::jsonb,'closeness','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',187,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'mixed_romance','相手から恋愛の話をされることはありますか？','concern','[]'::jsonb,'["mixed_signals"]'::jsonb,'romance','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',188,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'mixed_difference','他の人への接し方と、違うと感じることはありますか？','concern','[]'::jsonb,'["mixed_signals"]'::jsonb,'difference','textarea','[]'::jsonb,'{}'::jsonb,77,1,'覚えている範囲で、話せることだけで大丈夫です。',189,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'mixed_schedule','次の予定は、相手も一緒に考えてくれますか？','concern','[]'::jsonb,'["mixed_signals"]'::jsonb,'scheduling','textarea','[]'::jsonb,'{}'::jsonb,76,1,'覚えている範囲で、話せることだけで大丈夫です。',190,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'uncertain_hope','相手といるとき、どんな瞬間に心が落ち着きますか？','concern','[]'::jsonb,'["uncertainty"]'::jsonb,'comfort','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',191,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'uncertain_worry','今の関係で、無理をしていると感じることはありますか？','concern','[]'::jsonb,'["uncertainty"]'::jsonb,'strain','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',192,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'uncertain_priority','これから考えるうえで、一番大切にしたいことは何ですか？','concern','[]'::jsonb,'["uncertainty"]'::jsonb,'boundary','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',193,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'other_concern_since','気になり始めたのは、いつ頃ですか？','concern','[]'::jsonb,'["other"]'::jsonb,'change_since','textarea','[]'::jsonb,'{}'::jsonb,80,1,'覚えている範囲で、話せることだけで大丈夫です。',194,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'other_attempt','そのことについて、相手と話したことはありますか？','concern','[]'::jsonb,'["other"]'::jsonb,'asked','textarea','[]'::jsonb,'{}'::jsonb,79,1,'覚えている範囲で、話せることだけで大丈夫です。',195,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'other_hope','今、どんなことが分かると少し安心できそうですか？','concern','[]'::jsonb,'["other"]'::jsonb,'clarity','textarea','[]'::jsonb,'{}'::jsonb,78,1,'覚えている範囲で、話せることだけで大丈夫です。',196,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'check_busy','相手の忙しさについて、本人からどんな話を聞いていますか？','ai_followup','[]'::jsonb,'[]'::jsonb,'life_change','textarea','[]'::jsonb,'{}'::jsonb,50,1,'覚えている範囲で、話せることだけで大丈夫です。',197,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'check_tone','最近のやり取りで、相手はどんな言葉を使っていましたか？','ai_followup','[]'::jsonb,'[]'::jsonb,'last_words','textarea','[]'::jsonb,'{}'::jsonb,50,1,'覚えている範囲で、話せることだけで大丈夫です。',198,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'check_meeting','会っているときの相手の様子を、もう少し教えてください。','ai_followup','[]'::jsonb,'[]'::jsonb,'meeting_mood','textarea','[]'::jsonb,'{}'::jsonb,50,1,'覚えている範囲で、話せることだけで大丈夫です。',199,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'check_own','あなたからは、最近どんな内容を送っていますか？','ai_followup','[]'::jsonb,'[]'::jsonb,'own_message','textarea','[]'::jsonb,'{}'::jsonb,50,1,'覚えている範囲で、話せることだけで大丈夫です。',200,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'paid_own','最後にあなたから送ったのは、どんな内容でしたか？','paid_followup','[]'::jsonb,'[]'::jsonb,'own_message','textarea','[]'::jsonb,'{}'::jsonb,50,1,'覚えている範囲で、話せることだけで大丈夫です。',201,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'paid_words','相手から最後に言われた、印象に残っている言葉はありますか？','paid_followup','[]'::jsonb,'[]'::jsonb,'last_words','textarea','[]'::jsonb,'{}'::jsonb,50,1,'覚えている範囲で、話せることだけで大丈夫です。',202,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'paid_possible','次に会えそうなのは、どんなタイミングですか？','paid_followup','[]'::jsonb,'[]'::jsonb,'possible_date','textarea','[]'::jsonb,'{}'::jsonb,50,1,'覚えている範囲で、話せることだけで大丈夫です。',203,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'paid_impulse','今、ついしてしまいそうで気になっていることはありますか？','paid_followup','[]'::jsonb,'[]'::jsonb,'impulse','textarea','[]'::jsonb,'{}'::jsonb,50,1,'覚えている範囲で、話せることだけで大丈夫です。',204,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'paid_tell','相手に一番伝えたいことは何ですか？','paid_followup','[]'::jsonb,'[]'::jsonb,'tell','textarea','[]'::jsonb,'{}'::jsonb,50,1,'覚えている範囲で、話せることだけで大丈夫です。',205,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'paid_avoid','これから、一番避けたいのはどんなことですか？','paid_followup','[]'::jsonb,'[]'::jsonb,'avoid','textarea','[]'::jsonb,'{}'::jsonb,50,1,'覚えている範囲で、話せることだけで大丈夫です。',206,'v2' from public.diagnosis_types where slug='partner-mind';
insert into public.diagnosis_questions(diagnosis_type_id,required,question_key,question_text,phase,relationship_types,concern_types,followup_group,question_type,options_json,condition_json,priority,max_uses,placeholder,sort_order,flow_version) select id,false,'paid_line','直近のLINEは、どんな雰囲気でしたか？','paid_followup','[]'::jsonb,'[]'::jsonb,'reply_content','textarea','[]'::jsonb,'{}'::jsonb,50,1,'覚えている範囲で、話せることだけで大丈夫です。',207,'v2' from public.diagnosis_types where slug='partner-mind';

-- Defense in depth: no worker, including a stale deployment, can skip v2 paid questions.
create or replace function public.claim_report(p_diagnosis uuid,p_token uuid) returns setof public.paid_reports language sql set search_path='' as $$
 update public.paid_reports r set status='generating',attempts=attempts+1,lease_token=p_token,lease_until=now()+interval '5 minutes',updated_at=now()
 where r.diagnosis_id=p_diagnosis and r.attempts<5 and (r.status in ('queued','failed') or (r.status='generating' and r.lease_until<now())) and exists(select 1 from public.payments p where p.id=r.payment_id and p.status='paid') and exists(select 1 from public.diagnoses d where d.id=p_diagnosis and d.status<>'safety' and (d.question_flow_version='v1' or coalesce((d.question_flow_json->>'paid_completed')::boolean,false))) returning r.*;
$$;
